name: Matrix
on: [push]

jobs:
    node-matrix:
        continue-on-error: true
        strategy:
            matrix:
                os: [windows-latest, macos-latest, ubuntu-latest]
                node-version: [14, 16, 18]
        runs-on: ${{ matrix.os }}
        steps:
            - run: node -v
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - run: node -v
